# Generated by Django 4.0.6 on 2022-08-06 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0004_alldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowPersonality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_app.keyword')),
            ],
        ),
    ]
