# Generated by Django 4.0.6 on 2022-08-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0006_followpersonality_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='channe_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
