# Generated by Django 4.0.6 on 2022-08-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0007_keyword_channe_id_alter_keyword_keyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='channe_id',
            new_name='channel_id',
        ),
    ]
