# Generated by Django 4.0.6 on 2022-08-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0008_rename_channe_id_keyword_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='most_recent',
            field=models.BooleanField(default=False),
        ),
    ]
