# Generated by Django 4.0.6 on 2022-08-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0009_keyword_most_recent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='most_recent',
            field=models.BooleanField(default=True),
        ),
    ]
