# Generated by Django 4.0.6 on 2022-08-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0011_randomvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomvideo',
            name='video_thumbnail_pic',
        ),
        migrations.AddField(
            model_name='randomvideo',
            name='video_thumbnail_pic_url',
            field=models.URLField(default=''),
        ),
    ]
