# Generated by Django 4.0.6 on 2022-08-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0012_remove_randomvideo_video_thumbnail_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order_of_display',
            field=models.IntegerField(default=0),
        ),
    ]
