# Generated by Django 4.0.6 on 2022-08-19 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0013_category_order_of_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40)),
                ('order_of_display', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='randomvideo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube_app.randomcategory'),
        ),
    ]
