# Generated by Django 4.0.6 on 2022-08-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0014_randomcategory_randomvideo_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image_url', models.URLField()),
            ],
        ),
    ]
