# Generated by Django 4.0.6 on 2022-08-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0015_herosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='channel_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='herosection',
            name='channel_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='herosection',
            name='upload_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='herosection',
            name='video_description',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='herosection',
            name='video_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='herosection',
            name='video_title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image_url',
            field=models.URLField(default=''),
        ),
    ]
