# Generated by Django 4.0.6 on 2022-08-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0016_herosection_channel_id_herosection_channel_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Banner Image'),
        ),
    ]
