# Generated by Django 4.0.6 on 2022-08-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0018_alter_keyword_avatar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='avatar_image',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='banner_image',
        ),
        migrations.AddField(
            model_name='keyword',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload_images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='randomvideo',
            name='video_thumbnail_pic_local',
            field=models.ImageField(blank=True, null=True, upload_to='upload_images/', verbose_name='Thumbnail Image'),
        ),
    ]
