# Generated by Django 4.0.6 on 2022-08-26 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube_app', '0020_athleteprofilecategory_athleteprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowedAthletes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_app.athleteprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
