# Generated by Django 4.0.6 on 2022-08-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0021_followedathletes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomvideo',
            name='video_thumbnail_pic_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
