# Generated by Django 4.0.6 on 2022-08-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0023_category_random_category_alter_randomvideo_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='random_category',
            new_name='is_random',
        ),
    ]
