# Generated by Django 4.0.6 on 2022-08-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0024_rename_random_category_category_is_random'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomCategory',
        ),
    ]
