# Generated by Django 3.2.15 on 2022-09-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0025_delete_randomcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='video_description',
            field=models.CharField(max_length=1000),
        ),
    ]
