# Generated by Django 4.0.6 on 2022-09-03 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0028_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athleteprofile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterModelOptions(
            name='athleteprofilecategory',
            options={'verbose_name': 'Profile Category', 'verbose_name_plural': 'Profile Categories'},
        ),
        migrations.AlterModelOptions(
            name='followedathletes',
            options={'verbose_name': 'Followed Athlete', 'verbose_name_plural': 'Followed Athletes'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Hero Corousel', 'verbose_name_plural': 'Hero Corousels'},
        ),
        migrations.AlterModelOptions(
            name='randomvideo',
            options={'verbose_name': 'Managed Video', 'verbose_name_plural': 'Managed Videos'},
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='profile_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube_app.athleteprofilecategory'),
        ),
    ]
