# Generated by Django 4.0.6 on 2022-09-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0029_alter_athleteprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofilecategory',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
