# Generated by Django 3.2.15 on 2022-09-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0030_alter_athleteprofilecategory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followpersonality',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='followpersonality',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='FollowedAthletes',
        ),
        migrations.DeleteModel(
            name='FollowPersonality',
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
