# Generated by Django 3.2.15 on 2022-09-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0031_auto_20220907_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=400)),
            ],
        ),
    ]
