# Generated by Django 3.2.15 on 2022-09-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0035_auto_20220909_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='communityprofile',
            name='name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
