# Generated by Django 3.2.15 on 2022-09-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0036_auto_20220909_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofile',
            name='avatar_image',
            field=models.ImageField(default='upload_images/default.png', upload_to='upload_images/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='communityprofile',
            name='banner_image',
            field=models.ImageField(default='upload_images/default.png', upload_to='upload_images/', verbose_name='Banner Image'),
        ),
    ]
