# Generated by Django 3.2.15 on 2022-09-08 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0034_auto_20220908_0502'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowedCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_app.communityprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Followed Community',
                'verbose_name_plural': 'Followed Community',
            },
        ),
    ]
